### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by ttuygun** [elopez/enablewhatsappweb#2]
When I pinned web.whatsapp.com and restart the firefox, the page tells me "Download Chrome". But when I refreshed the page, problem is fixing. The pages which are pinned need to one refresh at least.

**Comment by elopez** [comment]
Hi, can you check if 0.1.3 solves this issue for you? There is an xpi you can use on the repo, and the new version should show up on addons.mozilla.org soon too.

**Comment by ttuygun** [comment]
Fixed it.

**Comment by elopez** [comment]
Ok, thanks for testing and reporting! :)
